/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class engine_util_Timer */

#ifndef _Included_engine_util_Timer
#define _Included_engine_util_Timer
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: useDefault */
/*
 * Class:     engine_util_Timer
 * Method:    getNativeTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_engine_util_Timer_getNativeTime
  (JNIEnv *, jclass);

/*
 * Class:     engine_util_Timer
 * Method:    getNativeResolution
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_engine_util_Timer_getNativeResolution
  (JNIEnv *, jclass);

/*
 * Class:     engine_util_Timer
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_engine_util_Timer_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
